#!/bin/sh
set -eu

: "${POSTGRES_PRIMARY_HOST:?POSTGRES_PRIMARY_HOST is required}"
: "${POSTGRES_REPLICATION_USER:?POSTGRES_REPLICATION_USER is required}"
: "${POSTGRES_REPLICATION_PASSWORD:?POSTGRES_REPLICATION_PASSWORD is required}"

POSTGRES_PRIMARY_PORT="${POSTGRES_PRIMARY_PORT:-5432}"
APPLICATION_NAME="${REPLICA_APPLICATION_NAME:-postgres-replica}"
RESEED="${REPLICA_FORCE_RESEED:-false}"
ROLE_WAIT_ATTEMPTS="${REPLICA_ROLE_WAIT_ATTEMPTS:-60}"
ROLE_WAIT_INTERVAL="${REPLICA_ROLE_WAIT_INTERVAL:-2}"

if [ "$(id -u)" = "0" ]; then
    mkdir -p "$PGDATA"
    chown -R postgres:postgres "$PGDATA"
    chmod 0700 "$PGDATA"
    exec gosu postgres "$0" "$@"
fi

PG_VERSION_FILE="$PGDATA/PG_VERSION"
STANDBY_SIGNAL_FILE="$PGDATA/standby.signal"
AUTO_CONF_FILE="$PGDATA/postgresql.auto.conf"

has_pg_version() {
    [ -s "$PG_VERSION_FILE" ]
}

has_standby_signal() {
    [ -f "$STANDBY_SIGNAL_FILE" ]
}

has_primary_conninfo() {
    [ -s "$AUTO_CONF_FILE" ] && grep -q "^primary_conninfo[[:space:]]*=" "$AUTO_CONF_FILE"
}

primary_conninfo_matches_expected() {
    has_primary_conninfo \
        && grep -q "host[[:space:]]*=[[:space:]]*$POSTGRES_PRIMARY_HOST" "$AUTO_CONF_FILE" \
        && grep -q "user[[:space:]]*=[[:space:]]*$POSTGRES_REPLICATION_USER" "$AUTO_CONF_FILE"
}

is_valid_pgdata() {
    has_pg_version && has_standby_signal && primary_conninfo_matches_expected
}

wait_for_replication_role() {
    attempt=1
    until PGPASSWORD="$POSTGRES_REPLICATION_PASSWORD" psql \
        --host="$POSTGRES_PRIMARY_HOST" \
        --port="$POSTGRES_PRIMARY_PORT" \
        --username="$POSTGRES_REPLICATION_USER" \
        --dbname=postgres \
        --tuples-only --no-align \
        --command="SELECT 1" >/dev/null 2>&1
    do
        if [ "$attempt" -ge "$ROLE_WAIT_ATTEMPTS" ]; then
            echo "ERROR: replication role '$POSTGRES_REPLICATION_USER' on '$POSTGRES_PRIMARY_HOST:$POSTGRES_PRIMARY_PORT' was not available after $ROLE_WAIT_ATTEMPTS attempts" >&2
            exit 1
        fi
        echo "waiting for replication role '$POSTGRES_REPLICATION_USER' on primary (attempt $attempt/$ROLE_WAIT_ATTEMPTS)"
        attempt=$((attempt + 1))
        sleep "$ROLE_WAIT_INTERVAL"
    done
}

run_basebackup() {
    wait_for_replication_role

    echo "starting pg_basebackup from $POSTGRES_PRIMARY_HOST:$POSTGRES_PRIMARY_PORT as $POSTGRES_REPLICATION_USER"
    PGPASSWORD="$POSTGRES_REPLICATION_PASSWORD" pg_basebackup \
        --host="$POSTGRES_PRIMARY_HOST" \
        --port="$POSTGRES_PRIMARY_PORT" \
        --username="$POSTGRES_REPLICATION_USER" \
        --pgdata="$PGDATA" \
        --format=plain \
        --wal-method=stream \
        --write-recovery-conf \
        --checkpoint=fast

    cat >> "$AUTO_CONF_FILE" <<EOF

# generated by replica-entrypoint.sh
primary_conninfo = 'host=$POSTGRES_PRIMARY_HOST port=$POSTGRES_PRIMARY_PORT user=$POSTGRES_REPLICATION_USER password=$POSTGRES_REPLICATION_PASSWORD application_name=$APPLICATION_NAME'
cluster_name = '$APPLICATION_NAME'
EOF
}

if has_pg_version; then
    if is_valid_pgdata; then
        echo "replica PGDATA is consistent; reusing existing base backup"
    else
        echo "ERROR: replica PGDATA contains PG_VERSION but is inconsistent:" >&2
        has_standby_signal || echo "  - missing or empty $STANDBY_SIGNAL_FILE" >&2
        primary_conninfo_matches_expected || echo "  - $AUTO_CONF_FILE does not contain a primary_conninfo for host '$POSTGRES_PRIMARY_HOST' and user '$POSTGRES_REPLICATION_USER'" >&2
        if [ "$RESEED" = "true" ]; then
            echo "REPLICA_FORCE_RESEED=true: wiping ONLY replica PGDATA and restarting pg_basebackup" >&2
            find "$PGDATA" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
        else
            echo "Set REPLICA_FORCE_RESEED=true to wipe ONLY the replica PGDATA and re-run pg_basebackup." >&2
            echo "Primary data is never modified." >&2
            exit 1
        fi
    fi
fi

if [ ! -s "$PG_VERSION_FILE" ]; then
    run_basebackup
fi

touch "$STANDBY_SIGNAL_FILE"
chmod 0700 "$PGDATA"

exec docker-entrypoint.sh postgres -c hot_standby=on
